const authRoutes = require('@routes/authRoutes')
const productRoutes = require('./routes/productRoutes')
const categoryRoutes = require('./routes/categoryRoutes')
const userRoutes = require('./routes/userRoutes')
const orderRoutes = require('./routes/orderRoutes')
const reviewRoutes = require('./routes/reviewRoutes')
const reviewTagRoutes = require('./routes/reviewTagRoutes')
const subscriberRoutes = require('./routes/subscriberRoutes')
const contactRoutes = require('./routes/contactRoutes')
const contentRoutes = require('./routes/contentRoutes')
const rewardRoutes = require('./routes/rewardRoutes')
const pointsRoutes = require('./routes/pointsRoutes')
const adminRoutes = require('./routes/adminRoutes')
const wishlistRoutes = require('./routes/wishlistRoutes')
const shopSettingsRoutes = require('./routes/shopSettingsRoutes')
const galleryRoutes = require('./routes/galleryRoutes')
const homepageSettingsRoutes = require('./routes/homepageSettingsRoutes')
const settingRoute = require('./routes/settingRoute')
const homepageImageRoutes = require('./routes/homepageImageRoutes')
const visitorRoutes = require('./routes/visitorRoutes')
const userNoteRoutes = require('./routes/userNoteRoutes')
const taxRoutes = require('./routes/taxRoutes')
const { getAllsettingImages } = require('./controllers/settingController')

module.exports = (app) => {
  // Public routes - no authentication required
  app.use('/api/shop-settings', shopSettingsRoutes)
  app.use('/api/homepage-settings', homepageSettingsRoutes)
  app.use('/api/tax', taxRoutes)
  app.use('/api/auth', authRoutes)
  app.use('/api/products', productRoutes)
  app.use('/api/categories', categoryRoutes)
  app.use('/api/reviews', reviewRoutes)
  app.use('/api/review-tags', reviewTagRoutes)
  app.use('/api/subscribers', subscriberRoutes)
  app.use('/api/contacts', contactRoutes)
  app.use('/api/content', contentRoutes)
  app.use('/api/gallery', galleryRoutes)
  app.use('/api/setting', settingRoute)
  app.use('/api/homepage-images', homepageImageRoutes)
  app.use('/api/visitors', visitorRoutes)
  app.get('/api/pagesetting', getAllsettingImages)
  
  // Protected routes - authentication required
  app.use('/api/users', userRoutes)
  app.use('/api/rewards', rewardRoutes)
  app.use('/api/points', pointsRoutes)
  app.use('/api/admin', adminRoutes)
  app.use('/api/wishlist', wishlistRoutes)
  app.use('/api/user-notes', userNoteRoutes)
  app.use('/api', orderRoutes) // Mounted on /api because routes already have /orders and /admin/orders paths

}
